language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql
matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: DB=pgsql

    - php: 5.4
      env: DB=sqlite

    - php: 5.4
      env: PHPCS=1

notifications:
  email: false
